openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
tags:
  - name: auth
    description: Authorization operations
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Login user
      description: >-
        Authorizes a user and returns token for accesing the API. The user must already exist in the system
      x-eov-operation-handler: authController
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 200
                    description: Status' code
                  message:
                    type: string
                    default: CREATED
                    description: Message
                  count:
                    type: integer
                    description: Total results count
                  data:
                    type: object
                    description: Result data




