env:
  browser: true
  commonjs: true
  es2021: true
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  import/no-dynamic-require: 0
  no-underscore-dangle : 0
  no-useless-escape: 0
  prefer-destructuring: 0
  max-len:
    - error
    - code : 200